name: mac

on: [push, pull_request]

env:
  BOOST_VERSION: 1_79_0

jobs:
  mac:

    env:
      VERSION: v0.26.0

    strategy:
      fail-fast: false
      matrix:
        xcode: ['11']

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout Snapcast
      uses: actions/checkout@v2
      with:
        repository: badaix/snapcast
        path: src/snapcast
        ref: ${{ env.VERSION }}
    - name: Setup environment
      run: |
        echo "SHA=$(git -C $GITHUB_WORKSPACE/src/snapcast rev-parse HEAD)" >> $GITHUB_ENV
    - name: Get dependencies
      run: brew install pkgconfig libsoxr ccache expat
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: boost_${{ env.BOOST_VERSION }}
        key: ${{ runner.os }}-boost
    - name: Get boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION//_/.}/source/boost_${BOOST_VERSION}.tar.bz2
        tar xjf boost_${BOOST_VERSION}.tar.bz2
    - name: Cache ccache
      id: cache-ccache
      uses: actions/cache@v2
      with:
        path: /Users/runner/.ccache
        key: ${{ runner.os }}-ccache-${{ env.SHA }}
        restore-keys: ${{ runner.os }}-ccache-
    #- name: ccache dump config
    #  run: ccache -p
    - name: cmake build
      run: cmake -S $GITHUB_WORKSPACE/src/snapcast -B build -DBOOST_ROOT=$GITHUB_WORKSPACE/boost_${BOOST_VERSION} -DCMAKE_BUILD_TYPE=Release -DREVISION=${{ env.SHA }} -DWERROR=ON -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_FLAGS="-I/usr/local/include -Wno-deprecated-declarations"
    - name: cmake make
      run: cmake --build build --parallel 3
