name: mac

on: [push, pull_request]

env:
  BOOST_VERSION: 1_81_0

jobs:
  mac:

    env:
      VERSION: develop

    strategy:
      fail-fast: false
      matrix:
        xcode: ['11']

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Snapcast
      uses: actions/checkout@v3
      with:
        repository: badaix/snapcast
        path: src/snapcast
        ref: ${{ env.VERSION }}
    - name: Setup environment
      run: |
        echo "SHA=$(git -C $GITHUB_WORKSPACE/src/snapcast rev-parse HEAD)" >> $GITHUB_ENV
        BOOST_DOT_VERSION=$(echo ${BOOST_VERSION} | sed 's/_/./g')
        echo "BOOST_DOT_VERSION=$BOOST_DOT_VERSION" >> $GITHUB_ENV
        echo "BOOST=boost_${BOOST_VERSION}" >> $GITHUB_ENV
    - name: Get dependencies
      run: brew install pkgconfig libsoxr ccache expat
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: ${{env.BOOST}}
        key: ${{ runner.os }}-boost
    - name: Get boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/${{env.BOOST_DOT_VERSION}}/source/${{env.BOOST}}.tar.bz2
        tar xjf ${{env.BOOST}}.tar.bz2
    - name: Cache ccache
      id: cache-ccache
      uses: actions/cache@v3
      with:
        path: /Users/runner/.ccache
        key: ${{ runner.os }}-ccache-${{ env.SHA }}
        restore-keys: ${{ runner.os }}-ccache-
    #- name: ccache dump config
    #  run: ccache -p
    - name: configure
      run: cmake -S $GITHUB_WORKSPACE/src/snapcast -B build -DBOOST_ROOT=$GITHUB_WORKSPACE/${{env.BOOST}} -DCMAKE_BUILD_TYPE=Release -DREVISION=${{ env.SHA }} -DWERROR=ON -DBUILD_TESTS=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_FLAGS="-I/usr/local/include -Wno-deprecated-declarations"
    - name: build
      run: cmake --build build --parallel 3
