name: Test Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - mips_24kc

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEED_DIR: "$GITHUB_WORKSPACE/openwrt/"
          PACKAGES: snapcast snapclient snapserver
          V: sc  # verbosity, see https://openwrt.org/docs/techref/buildroot#warnings_errors_and_tracing
          # avoid bug in git diff invocation
          NO_REFRESH_CHECK: 1
          NO_SHFMT_CHECK: 1

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          path: /**/*.ipk
          #path: bin/packages/${{ matrix.arch }}/packages/*.ipk
